### ISSUE TITLE
TypeError: Cannot read property 'cloudinary' of undefined

### ISSUE THREAD

**Issue by mmccoy** [rwatts3/orionjs-cloudinary#7]
Just spinning up a test with no code besides your boilerplate example:

```
{15:10}~/Development/misc/cloudinary-test ➭ meteor 
[[[[[ ~/Development/misc/cloudinary-test ]]]]]`

=> Started proxy.                             
=> Started MongoDB.                           
W20160308-15:11:05.552(-5)? (STDERR)          
W20160308-15:11:05.553(-5)? (STDERR) /Users/mmccoy/.meteor/packages/meteor-tool/.1.1.10.nozhqp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160308-15:11:05.553(-5)? (STDERR)            throw(ex);
W20160308-15:11:05.554(-5)? (STDERR)                  ^
W20160308-15:11:05.554(-5)? (STDERR) TypeError: Cannot read property 'cloudinary' of undefined
W20160308-15:11:05.554(-5)? (STDERR)     at Package (cloudinary.js:38:38)
W20160308-15:11:05.554(-5)? (STDERR)     at /Users/mmccoy/Development/misc/cloudinary-test/.meteor/local/build/programs/server/packages/rwatts_orionjs-cloudinary.js:109:4
W20160308-15:11:05.554(-5)? (STDERR)     at /Users/mmccoy/Development/misc/cloudinary-test/.meteor/local/build/programs/server/packages/rwatts_orionjs-cloudinary.js:119:3
W20160308-15:11:05.554(-5)? (STDERR)     at /Users/mmccoy/Development/misc/cloudinary-test/.meteor/local/build/programs/server/boot.js:242:10
W20160308-15:11:05.554(-5)? (STDERR)     at Array.forEach (native)
W20160308-15:11:05.554(-5)? (STDERR)     at Function._.each._.forEach (/Users/mmccoy/.meteor/packages/meteor-tool/.1.1.10.nozhqp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160308-15:11:05.554(-5)? (STDERR)     at /Users/mmccoy/Development/misc/cloudinary-test/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by mmccoy** [comment]
N/m, new to meteor, didn't know I had to pass in --settings :)

**Comment by romans127** [comment]
No problem. The new version of this package now requires you to pass the
settings because of the way I've structured it. I'm trying to prepare for
meteor 1.3 and the module approach that future Devs will be using while
using this package.

**Comment by mmccoy** [comment]
Thanks for the followup, do you happen to have a cloudinary Orion upload
provider example using this package I could look at?

**Comment by romans127** [comment]
This package tied directly to to the Orion provider in file system. So any
image attribute or file attribute is already wired in. Just add this
package pass your meteor settings and your all set. I don't have any
examples of building one personally outside of the default images , and
file attributes
